<?php

namespace Database\Seeders;

use App\Models\MazadQuestion;
use Illuminate\Database\Seeder;

class MazadQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ── Football ──
            [
                'text' => 'Football players who played for both Al Ahly and Zamalek',
                'text_ar' => 'لاعبين كرة قدم لعبوا للنادي الأهلي والزمالك',
                'category' => 'football',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'حسام حسن', 'hossam hassan',
                    'إبراهيم حسن', 'ibrahim hassan',
                    'رضا عبد العال', 'reda abdel aal', 'reda abdelaal',
                    'عبد الله السعيد', 'abdallah el said', 'abdallah el-said',
                    'محمود عبد المنعم كهربا', 'كهربا', 'kahraba', 'mahmoud kahraba',
                    'إمام عاشور', 'عاشور', 'imam ashour', 'emam ashour',
                    'أحمد حسن', 'ahmed hassan',
                    'عصام الحضري', 'essam el hadary', 'el hadary', 'الحضري',
                    'مؤمن زكريا', 'momen zakaria',
                    'جمال حمزة', 'gamal hamza',
                    'طارق السعيد', 'tarek el said',
                    'محمد صديق', 'mohamed sedik',
                    'إسلام الشاطر', 'eslam el shater',
                    'صبري رحيل', 'sabry raheel', 'sabry rahil',
                    'معتز إينو', 'إينو', 'moataz eno',
                    'حسين ياسر المحمدي', 'حسين ياسر', 'hussein yasser',
                    'أحمد حمودي', 'ahmed hamoudi',
                    'دومينيك دا سيلفا', 'dominique da silva',
                    'شريف أشرف', 'sherif ashraf',
                    'نادر السيد', 'nader el sayed',
                ],
            ],
            [
                'text' => 'Football players who won the Ballon d\'Or',
                'text_ar' => 'لاعبين كرة قدم فازوا بجائزة الكرة الذهبية',
                'category' => 'football',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'ليونيل ميسي', 'lionel messi', 'messi',
                    'كريستيانو رونالدو', 'cristiano ronaldo', 'ronaldo',
                    'لوكا مودريتش', 'luka modric', 'modric',
                    'كريم بنزيما', 'karim benzema', 'benzema',
                    'روبرت ليفاندوفسكي', 'robert lewandowski',
                    'زين الدين زيدان', 'zinedine zidane', 'zidane',
                    'رونالدينيو', 'ronaldinho',
                    'كاكا', 'kaka',
                    'ميشيل بلاتيني', 'michel platini',
                    'ماركو فان باستن', 'marco van basten',
                    'رونالدو نازاريو', 'ronaldo nazario',
                    'ريفالدو', 'rivaldo',
                ],
            ],
            [
                'text' => 'Countries that won the FIFA World Cup',
                'text_ar' => 'دول فازت بكأس العالم لكرة القدم',
                'category' => 'football',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'البرازيل', 'brazil',
                    'ألمانيا', 'germany',
                    'إيطاليا', 'italy',
                    'الأرجنتين', 'argentina',
                    'فرنسا', 'france',
                    'أوروغواي', 'uruguay',
                    'إنجلترا', 'england',
                    'إسبانيا', 'spain',
                ],
            ],
            [
                'text' => 'Football players whose name starts with M',
                'text_ar' => 'لاعبين كرة قدم يبدأ اسمهم بحرف الـ م',
                'category' => 'football',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'ميسي', 'messi',
                    'مبابي', 'mbappe',
                    'مودريتش', 'modric',
                    'مارادونا', 'maradona',
                    'ماني', 'mane',
                    'مولر', 'muller',
                    'ماركيزيو', 'marchisio',
                    'ماتيتش', 'matic',
                    'محمد صلاح', 'mohamed salah', 'mo salah',
                    'ماسكيرانو', 'mascherano',
                    'ميلنر', 'milner',
                    'مارسيلو', 'marcelo',
                ],
            ],
            // ── Entertainment ──
            [
                'text' => 'Egyptian actors whose name starts with A',
                'text_ar' => 'ممثلين مصريين يبدأ اسمهم بحرف الـ أ',
                'category' => 'entertainment',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'أحمد السقا', 'ahmed el sakka',
                    'أحمد حلمي', 'ahmed helmy',
                    'أحمد عز', 'ahmed ezz',
                    'أحمد مكي', 'ahmed mekky',
                    'أحمد رزق', 'ahmed rizk',
                    'أحمد آدم', 'ahmed adam',
                    'أمير كرارة', 'amir karara',
                    'أحمد فهمي', 'ahmed fahmy',
                    'أحمد زاهر', 'ahmed zaher',
                ],
            ],
            [
                'text' => 'Actors whose name starts with M',
                'text_ar' => 'ممثلين يبدأ اسمهم بحرف الـ م',
                'category' => 'entertainment',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'محمد رمضان', 'mohamed ramadan',
                    'محمد سعد', 'mohamed saad',
                    'محمد هنيدي', 'mohamed henedy',
                    'محمد إمام', 'mohamed imam',
                    'مصطفى شعبان', 'mostafa shaaban',
                    'ماجد الكدواني', 'maged el kedwany',
                    'مصطفى قمر', 'mostafa amar',
                    'محمود حميدة', 'mahmoud hemeida',
                    'محمود عبد العزيز', 'mahmoud abdel aziz',
                ],
            ],
            [
                'text' => 'Famous Egyptian movies from the 90s',
                'text_ar' => 'أفلام مصرية شهيرة من التسعينات',
                'category' => 'cinema',
                'difficulty' => 'hard',
                'accepted_answers' => [
                    'إسماعيلية رايح جاي', 'ismailia rayeh gay',
                    'صعيدي في الجامعة الأمريكية', 'saeedy fel gam3a',
                    'الناظر', 'el nazer',
                    'همام في أمستردام', 'hamam fi amsterdam',
                    'اللعب مع الكبار', 'ella3b maa el kobar',
                    'سمع هس', 'sama3 hoss',
                    'الإرهاب والكباب', 'terrorism and kebab',
                    'عريس من جهة أمنية', 'arees men geha amneya',
                    'أبو علي', 'abo ali',
                ],
            ],
            // ── Geography ──
            [
                'text' => 'Arab countries whose capital starts with B',
                'text_ar' => 'دول عربية عاصمتها تبدأ بحرف الـ ب',
                'category' => 'geography',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'لبنان', 'lebanon', 'بيروت', 'beirut',
                    'العراق', 'iraq', 'بغداد', 'baghdad',
                    'البحرين', 'bahrain',
                ],
            ],
            [
                'text' => 'Name as many European capital cities as you can',
                'text_ar' => 'اذكر أكبر عدد من عواصم الدول الأوروبية',
                'category' => 'geography',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'باريس', 'paris',
                    'لندن', 'london',
                    'برلين', 'berlin',
                    'مدريد', 'madrid',
                    'روما', 'rome',
                    'لشبونة', 'lisbon',
                    'أثينا', 'athens',
                    'فيينا', 'vienna',
                    'وارسو', 'warsaw',
                    'أوسلو', 'oslo',
                    'ستوكهولم', 'stockholm',
                    'كوبنهاغن', 'copenhagen',
                    'أمستردام', 'amsterdam',
                    'بروكسل', 'brussels',
                    'براغ', 'prague',
                    'بودابست', 'budapest',
                    'بوخارست', 'bucharest',
                    'دبلن', 'dublin',
                ],
            ],
            [
                'text' => 'Countries in Africa',
                'text_ar' => 'دول في قارة أفريقيا',
                'category' => 'geography',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'مصر', 'egypt',
                    'المغرب', 'morocco',
                    'الجزائر', 'algeria',
                    'تونس', 'tunisia',
                    'ليبيا', 'libya',
                    'السودان', 'sudan',
                    'نيجيريا', 'nigeria',
                    'جنوب أفريقيا', 'south africa',
                    'كينيا', 'kenya',
                    'غانا', 'ghana',
                    'إثيوبيا', 'ethiopia',
                    'تنزانيا', 'tanzania',
                    'الكاميرون', 'cameroon',
                    'السنغال', 'senegal',
                    'ساحل العاج', 'ivory coast',
                ],
            ],
            // ── General Knowledge ──
            [
                'text' => 'Colors of the rainbow',
                'text_ar' => 'ألوان قوس قزح',
                'category' => 'general',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'أحمر', 'red',
                    'برتقالي', 'orange',
                    'أصفر', 'yellow',
                    'أخضر', 'green',
                    'أزرق', 'blue',
                    'نيلي', 'indigo',
                    'بنفسجي', 'violet',
                ],
            ],
            [
                'text' => 'Planets in the solar system',
                'text_ar' => 'كواكب المجموعة الشمسية',
                'category' => 'general',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'عطارد', 'mercury',
                    'الزهرة', 'venus',
                    'الأرض', 'earth',
                    'المريخ', 'mars',
                    'المشتري', 'jupiter',
                    'زحل', 'saturn',
                    'أورانوس', 'uranus',
                    'نبتون', 'neptune',
                ],
            ],
            // ── Sports (Non-Football) ──
            [
                'text' => 'Tennis Grand Slam tournaments',
                'text_ar' => 'بطولات الجراند سلام في التنس',
                'category' => 'sports',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'ويمبلدون', 'wimbledon',
                    'رولان غاروس', 'roland garros', 'french open',
                    'أستراليا المفتوحة', 'australian open',
                    'أمريكا المفتوحة', 'us open',
                ],
            ],
            [
                'text' => 'Olympic sports',
                'text_ar' => 'رياضات أولمبية',
                'category' => 'sports',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'سباحة', 'swimming',
                    'ألعاب القوى', 'athletics', 'track and field',
                    'جمباز', 'gymnastics',
                    'كرة القدم', 'football', 'soccer',
                    'كرة السلة', 'basketball',
                    'كرة الطائرة', 'volleyball',
                    'التنس', 'tennis',
                    'الملاكمة', 'boxing',
                    'المصارعة', 'wrestling',
                    'الرماية', 'shooting',
                    'ركوب الخيل', 'equestrian',
                    'التجديف', 'rowing',
                    'رفع الأثقال', 'weightlifting',
                    'المبارزة', 'fencing',
                    'تايكوندو', 'taekwondo',
                    'جودو', 'judo',
                ],
            ],
            // ── Food ──
            [
                'text' => 'Famous Egyptian dishes',
                'text_ar' => 'أكلات مصرية شهيرة',
                'category' => 'food',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'كشري', 'koshari', 'koshary',
                    'فول', 'foul', 'ful',
                    'طعمية', 'taamiya', 'falafel',
                    'ملوخية', 'molokhia',
                    'محشي', 'mahshi',
                    'فتة', 'fattah',
                    'حمام محشي', 'stuffed pigeon',
                    'بسبوسة', 'basbousa',
                    'كنافة', 'kunafa',
                    'أم علي', 'om ali',
                    'شوربة لسان عصفور', 'orzo soup',
                ],
            ],
            // ── History ──
            [
                'text' => 'Ancient Egyptian pharaohs',
                'text_ar' => 'فراعنة مصر القديمة',
                'category' => 'history',
                'difficulty' => 'hard',
                'accepted_answers' => [
                    'توت عنخ آمون', 'tutankhamun',
                    'رمسيس الثاني', 'ramesses ii', 'ramses ii',
                    'كليوباترا', 'cleopatra',
                    'خوفو', 'khufu', 'cheops',
                    'حتشبسوت', 'hatshepsut',
                    'أخناتون', 'akhenaten',
                    'نفرتيتي', 'nefertiti',
                    'مينا', 'menes', 'narmer',
                    'تحتمس الثالث', 'thutmose iii',
                    'سنفرو', 'sneferu',
                ],
            ],
            // ── Music ──
            [
                'text' => 'Famous Arab singers',
                'text_ar' => 'مطربين عرب مشهورين',
                'category' => 'music',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'أم كلثوم', 'umm kulthum', 'oum kalthoum',
                    'عبد الحليم حافظ', 'abdel halim hafez',
                    'فيروز', 'fairuz',
                    'عمرو دياب', 'amr diab',
                    'محمد منير', 'mohamed mounir',
                    'نجاة الصغيرة', 'nagat el saghira',
                    'وردة الجزائرية', 'warda',
                    'كاظم الساهر', 'kazem el saher',
                    'إليسا', 'elissa',
                    'نانسي عجرم', 'nancy ajram',
                    'شيرين', 'sherine',
                    'تامر حسني', 'tamer hosny',
                ],
            ],
            // ── Science ──
            [
                'text' => 'Chemical elements',
                'text_ar' => 'عناصر كيميائية',
                'category' => 'science',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'هيدروجين', 'hydrogen',
                    'أكسجين', 'oxygen',
                    'نيتروجين', 'nitrogen',
                    'كربون', 'carbon',
                    'حديد', 'iron',
                    'ذهب', 'gold',
                    'فضة', 'silver',
                    'نحاس', 'copper',
                    'هيليوم', 'helium',
                    'كالسيوم', 'calcium',
                    'صوديوم', 'sodium',
                    'بوتاسيوم', 'potassium',
                ],
            ],
            // ── Language ──
            [
                'text' => 'Words that start with the letter Q in English',
                'text_ar' => 'كلمات تبدأ بحرف Q بالإنجليزية',
                'category' => 'language',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'queen', 'question', 'quick', 'quiet',
                    'quality', 'quarter', 'quote', 'quiz',
                    'queue', 'quit', 'quite', 'quest',
                    'quilt', 'quantum', 'quarrel',
                ],
            ],
            // ── Animals ──
            [
                'text' => 'Animals that live in the desert',
                'text_ar' => 'حيوانات تعيش في الصحراء',
                'category' => 'animals',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'جمل', 'camel',
                    'ثعلب الصحراء', 'fennec fox', 'فنك',
                    'عقرب', 'scorpion',
                    'سحلية', 'lizard',
                    'أفعى', 'snake',
                    'نسر', 'eagle',
                    'غزال', 'gazelle',
                    'أرنب بري', 'hare',
                    'ضب', 'monitor lizard',
                    'صقر', 'falcon',
                ],
            ],
            // ── Extra Entertainment (Actors) ──
            [
                'text' => 'Egyptian comedians',
                'text_ar' => 'ممثلين كوميديين مصريين',
                'category' => 'entertainment',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'عادل إمام', 'عادل امام', 'adel imam', 'adel emam', 'الزعيم', 'el zaim',
                    'سمير غانم', 'samir ghanem',
                    'محمد هنيدي', 'هنيدي', 'mohamed henedy', 'henedy',
                    'علاء ولي الدين', 'alaa wali el din', 'alaa waliy el din',
                    'أحمد حلمي', 'احمد حلمي', 'ahmed helmy', 'helmy',
                    'محمد سعد', 'mohamed saad', 'ellembey', 'اللمبي',
                    'إسماعيل ياسين', 'اسماعيل ياسين', 'ismail yassin', 'ismail yaseen', 'سمعة',
                    'فؤاد المهندس', 'fouad el mohandes',
                    'نجيب الريحاني', 'naguib el rihani',
                    'سعيد صالح', 'saeed saleh',
                    'يونس شلبي', 'younes shalaby',
                    'حسن حسني', 'hassan hosny',
                    'شيكو', 'chico',
                    'هشام ماجد', 'hesham maged',
                    'أحمد فهمي', 'ahmed fahmy',
                    'محمد عبد الرحمن', 'توتا', 'tota',
                    'علي ربيع', 'ali rabee',
                    'مصطفى خاطر', 'mostafa khater',
                ],
            ],
            [
                'text' => 'Arab female singers',
                'text_ar' => 'مطربات عربيات مشهورات',
                'category' => 'music',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'فيروز', 'fairuz', 'fayrouz',
                    'أم كلثوم', 'ام كلثوم', 'umm kulthum', 'oum kalthoum',
                    'نانسي عجرم', 'نانسي', 'nancy ajram', 'nancy',
                    'إليسا', 'elissa', 'elisa',
                    'شيرين عبد الوهاب', 'شيرين', 'sherine', 'sherine abdel wahab',
                    'أصالة نصري', 'أصالة', 'اصالة', 'assala', 'assala nasri',
                    'أنغام', 'angham',
                    'نجوى كرم', 'najwa karam',
                    'هيفاء وهبي', 'هيفاء', 'haifa wehbe', 'haifa',
                    'نوال الزغبي', 'nawal el zoghbi',
                    'لطيفة', 'latifa',
                    'سميرة سعيد', 'samira said', 'samira saeed',
                ],
            ],
            [
                'text' => 'Egyptian actors who starred in international movies',
                'text_ar' => 'ممثلين مصريين مثلوا في أفلام عالمية',
                'category' => 'entertainment',
                'difficulty' => 'hard',
                'accepted_answers' => [
                    'عمر الشريف', 'omar sharif', 'omar el sharif',
                    'خالد النبوي', 'khaled el nabawy', 'khaled nabawy',
                    'عمرو واكد', 'amr waked',
                    'جميل راتب', 'gamil rateb',
                    'رامي مالك', 'rami malek',
                    'مينا مسعود', 'mena massoud', 'mina massoud',
                    'سيد رجب', 'sayed ragab',
                    'أمير المصري', 'amir el masry', 'amir masry',
                ],
            ],
            // ── Extra Cinema (Movies) ──
            [
                'text' => 'Egyptian comedy movies',
                'text_ar' => 'أفلام كوميدية مصرية',
                'category' => 'cinema',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'الناظر', 'el nazer',
                    'صعيدي في الجامعة الأمريكية', 'صعيدي في الجامعة الامريكية', 'saeedy fel gam3a',
                    'غبي منه فيه', 'gaby meno feh',
                    'بوحة', 'boha', 'bouha',
                    'اللمبي', 'el lemby', 'ellemby',
                    'عسل إسود', 'عسل اسود', 'asal eswad',
                    'مطب صناعي', 'matab senai',
                    'لا تراجع ولا استسلام', 'la tarago3 wala esteslam',
                    'كدا رضا', 'keda reda',
                    'مرجان أحمد مرجان', 'morgan ahmed morgan',
                    'فول الصين العظيم', 'fool el seen el azeem',
                    'إكس لارج', 'x large',
                    'جعلتني مجرما', 'ga3alatny mogreman',
                    'طير إنت', 'طير انت', 'teer enta',
                    'البدلة', 'el badla',
                ],
            ],
            [
                'text' => 'Movies starring Adel Imam',
                'text_ar' => 'أفلام من بطولة عادل إمام',
                'category' => 'cinema',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'الإرهاب والكباب', 'el irhab wal kabab',
                    'السفارة في العمارة', 'el sefara fel omara',
                    'طيور الظلام', 'toyoor el zalam',
                    'عريس من جهة أمنية', 'عريس من جهة امنية', 'arees men geha amneya',
                    'التجربة الدنماركية', 'el tagroba el denmarkeya',
                    'مرجان أحمد مرجان', 'morgan ahmed morgan',
                    'حسن ومرقص', 'hassan wa morcos',
                    'اللعب مع الكبار', 'el laab maal kobar',
                    'بخيت وعديلة', 'bakhit wa adila',
                    'شمس الزناتي', 'shams el zanaty',
                    'سلام يا صاحبي', 'salam ya sahby',
                    'زهايمر', 'zahaymer',
                    'المتسول', 'el motasawel',
                    'الهلفوت', 'el halfoot',
                ],
            ],
            [
                'text' => 'Egyptian horror or thriller movies',
                'text_ar' => 'أفلام رعب أو إثارة مصرية',
                'category' => 'cinema',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'الفيل الأزرق', 'الفيل الازرق', 'el feel el azrak', 'blue elephant',
                    'تراب الماس', 'torab el mas', 'diamond dust',
                    'الحارث', 'el hares',
                    'خط دم', 'khot dam',
                    'الإنس والجن', 'الانس والجن', 'el ens wal gen',
                    '122', 'الـ122',
                    'كامب', 'camp',
                    'ورقة شفرة', 'warakat shafra',
                    'الأصليين', 'الاصليين', 'el aslyeen',
                    'ويجا', 'ouija', 'wega',
                ],
            ],
            [
                'text' => 'Egyptian action movies',
                'text_ar' => 'أفلام حركة وإثارة مصرية',
                'category' => 'cinema',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'ولاد رزق', 'welad rizk', 'welad rezg',
                    'الممر', 'el mamar',
                    'كازابلانكا', 'casablanca',
                    'حرب كرموز', 'harb kermoze',
                    'تيتو', 'tito',
                    'الجزيرة', 'el gazeera', 'el gezira',
                    'مافيا', 'mafia',
                    'ملاكي إسكندرية', 'malaki eskandareya',
                    'الخلية', 'el khalaya', 'el khaleya',
                ],
            ],
        ];

        foreach ($questions as $q) {
            MazadQuestion::updateOrCreate(
                ['text' => $q['text']],
                $q
            );
        }

        $this->command->info('Seeded ' . count($questions) . ' Mazad questions.');
    }
}
