<?php

namespace Database\Seeders;

use App\Models\MazadQuestion;
use Illuminate\Database\Seeder;

class MazadQuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // ── Football ──
            [
                'text' => 'Football players who played for both Al Ahly and Zamalek',
                'text_ar' => 'لاعبين كرة قدم لعبوا للنادي الأهلي والزمالك',
                'category' => 'football',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'عماد متعب', 'emad moteab',
                    'حسام حسن', 'hossam hassan',
                    'طاهر أبو زيد', 'taher abouzeid',
                    'عبد الله السعيد', 'abdallah el said',
                    'حسن شحاتة', 'hassan shehata',
                    'محمد صبري', 'mohamed sabry',
                    'أحمد حسام ميدو', 'ahmed hossam mido',
                    'إبراهيم حسن', 'ibrahim hassan',
                    'أيمن يونس', 'ayman younes',
                ],
            ],
            [
                'text' => 'Football players who won the Ballon d\'Or',
                'text_ar' => 'لاعبين كرة قدم فازوا بجائزة الكرة الذهبية',
                'category' => 'football',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'ليونيل ميسي', 'lionel messi', 'messi',
                    'كريستيانو رونالدو', 'cristiano ronaldo', 'ronaldo',
                    'لوكا مودريتش', 'luka modric', 'modric',
                    'كريم بنزيما', 'karim benzema', 'benzema',
                    'روبرت ليفاندوفسكي', 'robert lewandowski',
                    'زين الدين زيدان', 'zinedine zidane', 'zidane',
                    'رونالدينيو', 'ronaldinho',
                    'كاكا', 'kaka',
                    'ميشيل بلاتيني', 'michel platini',
                    'ماركو فان باستن', 'marco van basten',
                    'رونالدو نازاريو', 'ronaldo nazario',
                    'ريفالدو', 'rivaldo',
                ],
            ],
            [
                'text' => 'Countries that won the FIFA World Cup',
                'text_ar' => 'دول فازت بكأس العالم لكرة القدم',
                'category' => 'football',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'البرازيل', 'brazil',
                    'ألمانيا', 'germany',
                    'إيطاليا', 'italy',
                    'الأرجنتين', 'argentina',
                    'فرنسا', 'france',
                    'أوروغواي', 'uruguay',
                    'إنجلترا', 'england',
                    'إسبانيا', 'spain',
                ],
            ],
            [
                'text' => 'Football players whose name starts with M',
                'text_ar' => 'لاعبين كرة قدم يبدأ اسمهم بحرف الـ م',
                'category' => 'football',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'ميسي', 'messi',
                    'مبابي', 'mbappe',
                    'مودريتش', 'modric',
                    'مارادونا', 'maradona',
                    'ماني', 'mane',
                    'مولر', 'muller',
                    'ماركيزيو', 'marchisio',
                    'ماتيتش', 'matic',
                    'محمد صلاح', 'mohamed salah', 'mo salah',
                    'ماسكيرانو', 'mascherano',
                    'ميلنر', 'milner',
                    'مارسيلو', 'marcelo',
                ],
            ],
            // ── Entertainment ──
            [
                'text' => 'Egyptian actors whose name starts with A',
                'text_ar' => 'ممثلين مصريين يبدأ اسمهم بحرف الـ أ',
                'category' => 'entertainment',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'أحمد السقا', 'ahmed el sakka',
                    'أحمد حلمي', 'ahmed helmy',
                    'أحمد عز', 'ahmed ezz',
                    'أحمد مكي', 'ahmed mekky',
                    'أحمد رزق', 'ahmed rizk',
                    'أحمد آدم', 'ahmed adam',
                    'أمير كرارة', 'amir karara',
                    'أحمد فهمي', 'ahmed fahmy',
                    'أحمد زاهر', 'ahmed zaher',
                ],
            ],
            [
                'text' => 'Actors whose name starts with M',
                'text_ar' => 'ممثلين يبدأ اسمهم بحرف الـ م',
                'category' => 'entertainment',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'محمد رمضان', 'mohamed ramadan',
                    'محمد سعد', 'mohamed saad',
                    'محمد هنيدي', 'mohamed henedy',
                    'محمد إمام', 'mohamed imam',
                    'مصطفى شعبان', 'mostafa shaaban',
                    'ماجد الكدواني', 'maged el kedwany',
                    'مصطفى قمر', 'mostafa amar',
                    'محمود حميدة', 'mahmoud hemeida',
                    'محمود عبد العزيز', 'mahmoud abdel aziz',
                ],
            ],
            [
                'text' => 'Famous Egyptian movies from the 90s',
                'text_ar' => 'أفلام مصرية شهيرة من التسعينات',
                'category' => 'cinema',
                'difficulty' => 'hard',
                'accepted_answers' => [
                    'إسماعيلية رايح جاي', 'ismailia rayeh gay',
                    'صعيدي في الجامعة الأمريكية', 'saeedy fel gam3a',
                    'الناظر', 'el nazer',
                    'همام في أمستردام', 'hamam fi amsterdam',
                    'اللعب مع الكبار', 'ella3b maa el kobar',
                    'سمع هس', 'sama3 hoss',
                    'الإرهاب والكباب', 'terrorism and kebab',
                    'عريس من جهة أمنية', 'arees men geha amneya',
                    'أبو علي', 'abo ali',
                ],
            ],
            // ── Geography ──
            [
                'text' => 'Arab countries whose capital starts with B',
                'text_ar' => 'دول عربية عاصمتها تبدأ بحرف الـ ب',
                'category' => 'geography',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'لبنان', 'lebanon', 'بيروت', 'beirut',
                    'العراق', 'iraq', 'بغداد', 'baghdad',
                    'البحرين', 'bahrain',
                ],
            ],
            [
                'text' => 'Name as many European capital cities as you can',
                'text_ar' => 'اذكر أكبر عدد من عواصم الدول الأوروبية',
                'category' => 'geography',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'باريس', 'paris',
                    'لندن', 'london',
                    'برلين', 'berlin',
                    'مدريد', 'madrid',
                    'روما', 'rome',
                    'لشبونة', 'lisbon',
                    'أثينا', 'athens',
                    'فيينا', 'vienna',
                    'وارسو', 'warsaw',
                    'أوسلو', 'oslo',
                    'ستوكهولم', 'stockholm',
                    'كوبنهاغن', 'copenhagen',
                    'أمستردام', 'amsterdam',
                    'بروكسل', 'brussels',
                    'براغ', 'prague',
                    'بودابست', 'budapest',
                    'بوخارست', 'bucharest',
                    'دبلن', 'dublin',
                ],
            ],
            [
                'text' => 'Countries in Africa',
                'text_ar' => 'دول في قارة أفريقيا',
                'category' => 'geography',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'مصر', 'egypt',
                    'المغرب', 'morocco',
                    'الجزائر', 'algeria',
                    'تونس', 'tunisia',
                    'ليبيا', 'libya',
                    'السودان', 'sudan',
                    'نيجيريا', 'nigeria',
                    'جنوب أفريقيا', 'south africa',
                    'كينيا', 'kenya',
                    'غانا', 'ghana',
                    'إثيوبيا', 'ethiopia',
                    'تنزانيا', 'tanzania',
                    'الكاميرون', 'cameroon',
                    'السنغال', 'senegal',
                    'ساحل العاج', 'ivory coast',
                ],
            ],
            // ── General Knowledge ──
            [
                'text' => 'Colors of the rainbow',
                'text_ar' => 'ألوان قوس قزح',
                'category' => 'general',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'أحمر', 'red',
                    'برتقالي', 'orange',
                    'أصفر', 'yellow',
                    'أخضر', 'green',
                    'أزرق', 'blue',
                    'نيلي', 'indigo',
                    'بنفسجي', 'violet',
                ],
            ],
            [
                'text' => 'Planets in the solar system',
                'text_ar' => 'كواكب المجموعة الشمسية',
                'category' => 'general',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'عطارد', 'mercury',
                    'الزهرة', 'venus',
                    'الأرض', 'earth',
                    'المريخ', 'mars',
                    'المشتري', 'jupiter',
                    'زحل', 'saturn',
                    'أورانوس', 'uranus',
                    'نبتون', 'neptune',
                ],
            ],
            // ── Sports (Non-Football) ──
            [
                'text' => 'Tennis Grand Slam tournaments',
                'text_ar' => 'بطولات الجراند سلام في التنس',
                'category' => 'sports',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'ويمبلدون', 'wimbledon',
                    'رولان غاروس', 'roland garros', 'french open',
                    'أستراليا المفتوحة', 'australian open',
                    'أمريكا المفتوحة', 'us open',
                ],
            ],
            [
                'text' => 'Olympic sports',
                'text_ar' => 'رياضات أولمبية',
                'category' => 'sports',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'سباحة', 'swimming',
                    'ألعاب القوى', 'athletics', 'track and field',
                    'جمباز', 'gymnastics',
                    'كرة القدم', 'football', 'soccer',
                    'كرة السلة', 'basketball',
                    'كرة الطائرة', 'volleyball',
                    'التنس', 'tennis',
                    'الملاكمة', 'boxing',
                    'المصارعة', 'wrestling',
                    'الرماية', 'shooting',
                    'ركوب الخيل', 'equestrian',
                    'التجديف', 'rowing',
                    'رفع الأثقال', 'weightlifting',
                    'المبارزة', 'fencing',
                    'تايكوندو', 'taekwondo',
                    'جودو', 'judo',
                ],
            ],
            // ── Food ──
            [
                'text' => 'Famous Egyptian dishes',
                'text_ar' => 'أكلات مصرية شهيرة',
                'category' => 'food',
                'difficulty' => 'easy',
                'accepted_answers' => [
                    'كشري', 'koshari', 'koshary',
                    'فول', 'foul', 'ful',
                    'طعمية', 'taamiya', 'falafel',
                    'ملوخية', 'molokhia',
                    'محشي', 'mahshi',
                    'فتة', 'fattah',
                    'حمام محشي', 'stuffed pigeon',
                    'بسبوسة', 'basbousa',
                    'كنافة', 'kunafa',
                    'أم علي', 'om ali',
                    'شوربة لسان عصفور', 'orzo soup',
                ],
            ],
            // ── History ──
            [
                'text' => 'Ancient Egyptian pharaohs',
                'text_ar' => 'فراعنة مصر القديمة',
                'category' => 'history',
                'difficulty' => 'hard',
                'accepted_answers' => [
                    'توت عنخ آمون', 'tutankhamun',
                    'رمسيس الثاني', 'ramesses ii', 'ramses ii',
                    'كليوباترا', 'cleopatra',
                    'خوفو', 'khufu', 'cheops',
                    'حتشبسوت', 'hatshepsut',
                    'أخناتون', 'akhenaten',
                    'نفرتيتي', 'nefertiti',
                    'مينا', 'menes', 'narmer',
                    'تحتمس الثالث', 'thutmose iii',
                    'سنفرو', 'sneferu',
                ],
            ],
            // ── Music ──
            [
                'text' => 'Famous Arab singers',
                'text_ar' => 'مطربين عرب مشهورين',
                'category' => 'music',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'أم كلثوم', 'umm kulthum', 'oum kalthoum',
                    'عبد الحليم حافظ', 'abdel halim hafez',
                    'فيروز', 'fairuz',
                    'عمرو دياب', 'amr diab',
                    'محمد منير', 'mohamed mounir',
                    'نجاة الصغيرة', 'nagat el saghira',
                    'وردة الجزائرية', 'warda',
                    'كاظم الساهر', 'kazem el saher',
                    'إليسا', 'elissa',
                    'نانسي عجرم', 'nancy ajram',
                    'شيرين', 'sherine',
                    'تامر حسني', 'tamer hosny',
                ],
            ],
            // ── Science ──
            [
                'text' => 'Chemical elements',
                'text_ar' => 'عناصر كيميائية',
                'category' => 'science',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'هيدروجين', 'hydrogen',
                    'أكسجين', 'oxygen',
                    'نيتروجين', 'nitrogen',
                    'كربون', 'carbon',
                    'حديد', 'iron',
                    'ذهب', 'gold',
                    'فضة', 'silver',
                    'نحاس', 'copper',
                    'هيليوم', 'helium',
                    'كالسيوم', 'calcium',
                    'صوديوم', 'sodium',
                    'بوتاسيوم', 'potassium',
                ],
            ],
            // ── Language ──
            [
                'text' => 'Words that start with the letter Q in English',
                'text_ar' => 'كلمات تبدأ بحرف Q بالإنجليزية',
                'category' => 'language',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'queen', 'question', 'quick', 'quiet',
                    'quality', 'quarter', 'quote', 'quiz',
                    'queue', 'quit', 'quite', 'quest',
                    'quilt', 'quantum', 'quarrel',
                ],
            ],
            // ── Animals ──
            [
                'text' => 'Animals that live in the desert',
                'text_ar' => 'حيوانات تعيش في الصحراء',
                'category' => 'animals',
                'difficulty' => 'medium',
                'accepted_answers' => [
                    'جمل', 'camel',
                    'ثعلب الصحراء', 'fennec fox', 'فنك',
                    'عقرب', 'scorpion',
                    'سحلية', 'lizard',
                    'أفعى', 'snake',
                    'نسر', 'eagle',
                    'غزال', 'gazelle',
                    'أرنب بري', 'hare',
                    'ضب', 'monitor lizard',
                    'صقر', 'falcon',
                ],
            ],
        ];

        foreach ($questions as $q) {
            MazadQuestion::updateOrCreate(
                ['text' => $q['text']],
                $q
            );
        }

        $this->command->info('Seeded ' . count($questions) . ' Mazad questions.');
    }
}
